import Head from "next/head";
import Message from "../components/message";
import { useEffect, useState } from "react";
import { db } from "../utils/firebase";
import { collection, onSnapshot, orderBy, query } from "firebase/firestore";
import Link from "next/link";
import styles from '../styles/Home.module.css';

// Home page
export default function Home() {

  const [allPosts, setAllPosts] = useState([]);

  // get ALL user comments (tweets) from the firestore database
  const getPosts = async () => {
    const collectionRef = collection(db, 'posts');
    const q = query(collectionRef, orderBy('timestamp', 'desc'));
    // updates data in real time using snapshots
    const unsubscribe = onSnapshot(q, (snapshot) => {
      // returns array of all individual documents. passing in the data
      // in each document
      // 2nd parameter is the key id of the document
      setAllPosts(snapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id })))
    });
    return unsubscribe;
  }

  useEffect(() => {
    getPosts();
  }, []);

  // Returns the replies of other users, and shows how many replies there are
  // the "?" prevents the webpage from displaying an error since all replies are 0 initially
  return (

    <div>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <main>
        <h1 className={styles.title}>
          Welcome to Talking Points!
        </h1>

        <p className={styles.description}>
          <code>Get started by talking about the Topic of the day!</code>
        </p>

      </main>


      <div className="my-12 text-lg font-medium">
        <h2 className="text-center text-4xl font-bold">Today's Topic</h2>
        <h2 className="my-4 text-center text-2xl">Video games!</h2>
        {allPosts.map((post) => (
          <Message key={post.id} {...post}>
            <Link href={{ pathname: `/${post.id}`, query: { ...post } }}>
              <button>
                {post.comments?.length > 0 ? post.comments?.length : 0} Replies
              </button>
            </Link>
          </Message>
        ))}

      </div>
    </div>


  )
}
